const forms = require('@tailwindcss/forms')
const containerQueries = require('@tailwindcss/container-queries')

module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,html,txt}'],
  safelist: [
    'animate-in', 'fade-in', 'slide-in-from-right-4', 'duration-500',
    'animate-bounce', 'opacity-0', 'pointer-events-none', 'hidden'
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#eebd94',
        'on-secondary': '#432c00',
        'primary-fixed': '#d6e3ff',
        'primary-container': '#0b1f3a',
        'on-tertiary-container': '#a87e59',
        'inverse-surface': '#e4e2e5',
        'secondary-container': '#8e6200',
        'error-container': '#93000a',
        'surface-bright': '#39393b',
        'inverse-primary': '#4d5f7d',
        'outline': '#8e9098',
        'on-primary': '#1f314d',
        'surface-container-highest': '#343537',
        'primary-fixed-dim': '#b5c7ea',
        'tertiary-container': '#321800',
        'on-primary-fixed': '#071c36',
        'background': '#131315',
        'tertiary': '#eebd94',
        'surface-container-lowest': '#0d0e10',
        'on-error-container': '#ffdad6',
        'on-secondary-container': '#ffe9cb',
        'on-tertiary-fixed': '#2e1500',
        'error': '#ffb4ab',
        'outline-variant': '#44474d',
        'on-secondary-fixed': '#281900',
        'on-surface-variant': '#c4c6ce',
        'on-tertiary-fixed-variant': '#613f20',
        'on-error': '#690005',
        'surface-container-high': '#292a2c',
        'on-primary-container': '#7587a7',
        'tertiary-fixed': '#ffdcc1',
        'primary': '#b5c7ea',
        'secondary-fixed': '#ffdeac',
        'secondary': '#f5bd5c',
        'on-tertiary': '#47290c',
        'surface-variant': '#343537',
        'surface-tint': '#b5c7ea',
        'on-surface': '#e4e2e5',
        'on-primary-fixed-variant': '#364764',
        'surface-container': '#1f1f22',
        'inverse-on-surface': '#303033',
        'secondary-fixed-dim': '#f5bd5c',
        'surface-dim': '#131315',
        'on-background': '#e4e2e5',
        'surface': '#131315',
        'on-secondary-fixed-variant': '#5f4100',
        'surface-container-low': '#1b1b1e',
      },
      borderRadius: {
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
      },
      spacing: {
        'container-max': '1440px',
        'section-gap': '160px',
        gutter: '32px',
        'margin-edge': '64px',
        'element-gap': '24px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Fraunces', 'serif'],
        'display-lg-mobile': ['Fraunces', 'serif'],
        'headline-sm': ['Fraunces', 'serif'],
        eyebrow: ['Inter', 'sans-serif'],
        'headline-md': ['Fraunces', 'serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-numeric': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '500' }],
        'display-lg-mobile': ['44px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-sm': ['28px', { lineHeight: '1.4', fontWeight: '400' }],
        eyebrow: ['12px', { lineHeight: '1', letterSpacing: '0.2em', fontWeight: '600' }],
        'headline-md': ['40px', { lineHeight: '1.3', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-numeric': ['14px', { lineHeight: '1', fontWeight: '500' }],
      },
    },
  },
  plugins: [forms, containerQueries],
}
